services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garage_log
    ports:
      - "5432:5432"
    volumes:
      - garage_log_pg:/var/lib/postgresql/data

volumes:
  garage_log_pg:
